# Generated by Django 2.1 on 2018-08-07 23:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('siteapp', '0001_initial'), ('siteapp', '0002_homepage'), ('siteapp', '0003_homepage_page_slider'), ('siteapp', '0004_auto_20180803_0452'), ('siteapp', '0005_auto_20180803_0456'), ('siteapp', '0006_archiveprojects'), ('siteapp', '0007_auto_20180803_0512'), ('siteapp', '0008_auto_20180803_0523'), ('siteapp', '0009_auto_20180803_0530'), ('siteapp', '0010_auto_20180803_0532'), ('siteapp', '0011_homeslider_slide_image'), ('siteapp', '0012_auto_20180803_1707'), ('siteapp', '0013_auto_20180807_2138'), ('siteapp', '0014_siteoption'), ('siteapp', '0015_auto_20180807_2202'), ('siteapp', '0016_archiveservice'), ('siteapp', '0017_auto_20180807_2244'), ('siteapp', '0018_auto_20180807_2324'), ('siteapp', '0019_auto_20180807_2331')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(help_text='Enter the title', max_length=60)),
                ('slide_description', models.TextField(help_text='Enter the descrition', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(help_text='Enter the project title', max_length=150)),
                ('project_description', models.TextField(max_length=10000)),
                ('project_slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('site_option_name', models.CharField(help_text='Enter unique option name', max_length=100, primary_key=True, serialize=False)),
                ('site_option_value', models.TextField(help_text='Enter the value for the option', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_name', models.CharField(help_text='Enter unique banner name', max_length=100, primary_key=True, serialize=False)),
                ('banner_title', models.CharField(help_text='Enter the title for banner', max_length=500)),
                ('banner_description', models.TextField(help_text='Enter the description for banner', max_length=2000)),
                ('banner_button_name', models.CharField(help_text='Enter the button name', max_length=100)),
                ('banner_button_url', models.CharField(help_text='Enter the button URL', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(help_text='Enter the service title', max_length=200)),
                ('service_description', tinymce.models.HTMLField()),
                ('service_slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(help_text='Enter the post title', max_length=500)),
                ('service_description', tinymce.models.HTMLField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
    ]
