# Generated by Django 2.1 on 2018-09-04 22:47

import colorful.fields
from django.db import migrations, models
import siteapp.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(help_text='Enter the post title', max_length=500, unique=True)),
                ('post_content', tinymce.models.HTMLField()),
                ('post_excerpt', models.CharField(help_text='Enter the post excerpt', max_length=150, null=True)),
                ('post_thumbnail', models.ImageField(default='http://placehold.it/350x450/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_thumbnail_image)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(help_text='Enter the project title', max_length=150, unique=True)),
                ('project_content', tinymce.models.HTMLField()),
                ('project_excerpt', models.CharField(help_text='Enter the project excerpt', max_length=150, null=True)),
                ('project_thumbnail', models.ImageField(default='http://placehold.it/350x450/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_thumbnail_image)),
                ('project_slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(help_text='Enter the service title', max_length=200, unique=True)),
                ('service_content', tinymce.models.HTMLField()),
                ('service_excerpt', models.CharField(help_text='Enter the service excerpt', max_length=150, null=True)),
                ('service_thumbnail', models.ImageField(default='http://placehold.it/1000x600/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_thumbnail_image)),
                ('service_icon', models.ImageField(default='http://placehold.it/500x500/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_icon_image)),
                ('service_slug', models.SlugField(max_length=200, null=True)),
                ('service_background_color', colorful.fields.RGBColorField(default='#FFFFFF')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_name', models.CharField(help_text='Enter unique banner name', max_length=100, primary_key=True, serialize=False)),
                ('banner_title', models.CharField(help_text='Enter the title for banner', max_length=500)),
                ('banner_content', tinymce.models.HTMLField()),
                ('banner_thumbnail', models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_thumbnail_image)),
                ('banner_button_name', models.CharField(help_text='Enter the button name', max_length=100)),
                ('banner_button_url', models.CharField(help_text='Enter the button URL', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(help_text='Enter the title', max_length=60)),
                ('slide_content', models.TextField(help_text='Enter the descrition', max_length=150)),
                ('slide_image', models.ImageField(default='no-img.jpg', upload_to=siteapp.models.upload_thumbnail_image)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(help_text='Enter the page title', max_length=500, unique=True)),
                ('page_content', tinymce.models.HTMLField()),
                ('page_excerpt', models.CharField(help_text='Enter the page excerpt', max_length=150, null=True)),
                ('page_thumbnail', models.ImageField(default='http://placehold.it/1000x600/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_thumbnail_image)),
                ('page_date', models.DateTimeField(auto_now_add=True)),
                ('page_slug', models.SlugField(max_length=200, null=True)),
                ('page_template', models.CharField(choices=[('page-template/template-thankyou.html', 'template-thankyou'), ('page-template/template-default.html', 'template-default'), ('page-template/template-contact.html', 'template-contact')], default='default.html', help_text='Page template', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(max_length=200)),
                ('prospect_last_name', models.CharField(max_length=200)),
                ('prospect_email', models.CharField(max_length=200)),
                ('prospect_phone', models.CharField(max_length=15)),
                ('prospect_website', models.CharField(max_length=200)),
                ('prospect_message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('site_option_name', models.CharField(help_text='Enter unique option name', max_length=100, primary_key=True, serialize=False)),
                ('site_option_value', models.TextField(help_text='Enter the value for the option', max_length=1000)),
            ],
        ),
    ]
