# Generated by Django 2.1 on 2018-08-08 00:01

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial_squashed_0019_auto_20180807_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='service_thumbnail',
            field=models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_image_post),
        ),
        migrations.AddField(
            model_name='archiveproject',
            name='project_thumbnail',
            field=models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_image_project),
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='service_icon',
            field=models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_icon_service),
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='service_thumbnail',
            field=models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_image_service),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='slide_image',
            field=models.ImageField(default='no-img.jpg', upload_to=siteapp.models.upload_image_slider),
        ),
    ]
