# Generated by Django 2.1 on 2018-10-03 17:53

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_thumbnail',
            field=filebrowser.fields.FileBrowseField(max_length=500, null=True, verbose_name='Banner image (450x450)'),
        ),
    ]
