# Generated by Django 2.1 on 2018-08-08 00:08

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20180808_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_thumbnail',
            field=models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_image_banner),
        ),
    ]
