# Generated by Django 2.1 on 2018-09-04 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20180904_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospect_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
