# Generated by Django 2.1 on 2018-08-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_banner_banner_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivepost',
            old_name='service_description',
            new_name='post_description',
        ),
        migrations.RenameField(
            model_name='archivepost',
            old_name='service_thumbnail',
            new_name='post_thumbnail',
        ),
    ]
