# Generated by Django 2.1 on 2018-09-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_prospect_prospect_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivepost',
            old_name='post_date',
            new_name='post_created_at',
        ),
        migrations.AddField(
            model_name='archivepost',
            name='post_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
