# Generated by Django 2.1 on 2018-08-08 00:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20180808_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveproject',
            name='project_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
