# Generated by Django 2.1 on 2018-09-04 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20180904_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveservice',
            name='service_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='service_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
