# Generated by Django 2.1 on 2018-08-08 00:25

from django.db import migrations, models
import siteapp.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_auto_20180808_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.CharField(help_text='Enter the page title', max_length=500)),
                ('page_content', tinymce.models.HTMLField()),
                ('page_thumbnail', models.ImageField(default='no-img.png', upload_to=siteapp.models.upload_image_page)),
                ('page_date', models.DateTimeField(auto_now_add=True)),
                ('page_slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='archivepost',
            old_name='post_description',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='archiveproject',
            old_name='project_description',
            new_name='project_content',
        ),
        migrations.RenameField(
            model_name='archiveservice',
            old_name='service_description',
            new_name='service_content',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner_description',
            new_name='banner_content',
        ),
        migrations.RenameField(
            model_name='homeslider',
            old_name='slide_description',
            new_name='slide_content',
        ),
    ]
