# Generated by Django 2.1 on 2018-09-05 08:52

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_auto_20180904_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_thumbnail',
            field=models.ImageField(default='http://placehold.it/450x350/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
    ]
