# Generated by Django 2.1 on 2018-08-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_auto_20180808_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiveproject',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
