# Generated by Django 2.1 on 2018-09-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_auto_20180905_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_content',
            field=models.TextField(help_text='Enter the description', max_length=1000),
        ),
    ]
