# Generated by Django 2.1 on 2018-09-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_auto_20180906_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveproject',
            name='project_url',
            field=models.CharField(blank=True, help_text='Enter the project URL', max_length=300, null=True),
        ),
    ]
