# Generated by Django 2.1 on 2018-08-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_auto_20180808_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(help_text='Enter the page title', max_length=500, unique=True),
        ),
    ]
