# Generated by Django 2.1 on 2018-09-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0009_archiveproject_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='post_excerpt',
            field=models.TextField(help_text='Enter the post excerpt', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='archiveproject',
            name='project_excerpt',
            field=models.TextField(help_text='Enter the project excerpt', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='archiveservice',
            name='service_excerpt',
            field=models.TextField(help_text='Enter the service excerpt', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_excerpt',
            field=models.TextField(help_text='Enter the page excerpt', max_length=150, null=True),
        ),
    ]
