# Generated by Django 2.1 on 2018-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_auto_20180906_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospect_design_required',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='prospect',
            name='prospect_type',
            field=models.CharField(default='Contacto', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_template',
            field=models.CharField(help_text='Page template', max_length=1000),
        ),
    ]
