# Generated by Django 2.1 on 2018-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_auto_20180906_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_template',
            field=models.CharField(choices=[('page-template/template-thankyou.html', 'template-thankyou'), ('page-template/template-contact.html', 'template-contact'), ('page-template/template-default.html', 'template-default')], default='default.html', help_text='Page template', max_length=1000),
        ),
    ]
