# Generated by Django 2.1 on 2018-08-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0010_page_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_template',
            field=models.CharField(choices=[('page-template/default.html', 'default'), ('page-template/template-privacy.html', 'template-privacy'), ('page-template/template-contact.html', 'template-contact')], default='default.html', help_text='Page template', max_length=1000),
        ),
    ]
