# Generated by Django 2.1 on 2018-08-21 04:44

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_auto_20180809_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveproject',
            name='project_background_color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
        ),
    ]
