# Generated by Django 2.1 on 2018-09-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_auto_20180907_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospect_total_pages',
            field=models.CharField(default='', max_length=100),
        ),
    ]
