# Generated by Django 2.1 on 2018-09-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_auto_20180906_0749'),
        ('siteapp', '0012_prospect_prospect_total_pages'),
    ]

    operations = [
    ]
