# Generated by Django 2.1 on 2018-09-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0012_prospect_prospect_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='post_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending'), ('trash', 'Trash')], default='publish', max_length=30),
        ),
    ]
