# Generated by Django 2.1 on 2018-09-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_archivepost_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='post_author',
            field=models.CharField(default='', help_text='Enter the author', max_length=200),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='post_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending'), ('trash', 'Trash')], default='publish', help_text='Chose the status', max_length=30),
        ),
    ]
