# Generated by Django 2.1 on 2018-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_auto_20180821_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(max_length=200)),
                ('prospect_last_name', models.CharField(max_length=200)),
                ('prospect_email', models.CharField(max_length=200)),
                ('prospect_phone', models.CharField(max_length=15)),
                ('prospect_website', models.CharField(max_length=200)),
                ('prospect_message', models.TextField(max_length=5000)),
            ],
        ),
    ]
