# Generated by Django 2.1 on 2018-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0014_auto_20180910_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='post_author',
            field=models.CharField(blank=True, default='', help_text='Enter the author', max_length=200),
        ),
    ]
