# Generated by Django 2.1 on 2018-09-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0015_auto_20180910_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='post_keywords',
            field=models.TextField(blank=True, default='', help_text='Enter the keywords', max_length=300),
        ),
    ]
