# Generated by Django 2.1 on 2018-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0016_archivepost_post_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveproject',
            name='project_author',
            field=models.CharField(blank=True, default='', help_text='Enter the author', max_length=200),
        ),
        migrations.AddField(
            model_name='archiveproject',
            name='project_keywords',
            field=models.TextField(blank=True, default='', help_text="Enter the keywords, example: 'development, code, services'", max_length=300),
        ),
        migrations.AddField(
            model_name='archiveproject',
            name='project_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending'), ('trash', 'Trash')], default='publish', help_text='Chose the status', max_length=30),
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='service_author',
            field=models.CharField(blank=True, default='', help_text='Enter the author', max_length=200),
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='service_keywords',
            field=models.TextField(blank=True, default='', help_text="Enter the keywords, example: 'development, code, services'", max_length=300),
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='service_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending'), ('trash', 'Trash')], default='publish', help_text='Chose the status', max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='page_author',
            field=models.CharField(blank=True, default='', help_text='Enter the author', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='page_keywords',
            field=models.TextField(blank=True, default='', help_text="Enter the keywords, example: 'development, code, services'", max_length=300),
        ),
        migrations.AddField(
            model_name='page',
            name='page_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending'), ('trash', 'Trash')], default='publish', help_text='Chose the status', max_length=30),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='post_keywords',
            field=models.TextField(blank=True, default='', help_text="Enter the keywords, example: 'development, code, services'", max_length=300),
        ),
    ]
