# Generated by Django 2.1 on 2018-08-28 23:10

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_auto_20180828_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='post_thumbnail',
            field=models.ImageField(default='http://placehold.it/350x450/7b7b7b/DADADA/?text=350x450', upload_to=siteapp.models.upload_image_post),
        ),
    ]
