# Generated by Django 2.1 on 2018-09-18 21:32

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_auto_20180910_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveproject',
            name='project_archive_thumbnail',
            field=models.ImageField(default='http://placehold.it/350x450/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_archive_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='post_thumbnail',
            field=models.ImageField(default='http://placehold.it/350x450/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='archiveproject',
            name='project_thumbnail',
            field=models.ImageField(default='http://placehold.it/1000x333/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='archiveservice',
            name='service_icon',
            field=models.ImageField(default='http://placehold.it/500x500/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_icon_image),
        ),
        migrations.AlterField(
            model_name='archiveservice',
            name='service_thumbnail',
            field=models.ImageField(default='http://placehold.it/1000x600/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_thumbnail',
            field=models.ImageField(default='http://placehold.it/450x350/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='slide_image',
            field=models.ImageField(default='http://placehold.it/350x350/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_thumbnail',
            field=models.ImageField(default='http://placehold.it/1000x600/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
    ]
