# Generated by Django 2.1 on 2018-09-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0013_merge_20180906_2252'),
        ('siteapp', '0017_auto_20180910_2252'),
    ]

    operations = [
    ]
