# Generated by Django 2.1 on 2018-09-18 21:39

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0018_auto_20180918_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='post_archive_thumbnail',
            field=models.ImageField(default='http://placehold.it/350x450/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_archive_thumbnail_image),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='post_thumbnail',
            field=models.ImageField(default='http://placehold.it/1000x333/bfbfbf/bfbfbf/?text=RW', upload_to=siteapp.models.upload_thumbnail_image),
        ),
    ]
