# Generated by Django 2.1 on 2018-08-28 23:31

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0018_auto_20180828_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='post_thumbnail',
            field=models.ImageField(default='http://placehold.it/350x450/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_image_post),
        ),
        migrations.AlterField(
            model_name='archiveproject',
            name='project_thumbnail',
            field=models.ImageField(default='http://placehold.it/350x450/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_image_project),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_thumbnail',
            field=models.ImageField(default='http://placehold.it/1000x600/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_image_page),
        ),
    ]
