# Generated by Django 2.1 on 2018-08-28 23:33

from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0019_auto_20180828_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveservice',
            name='service_thumbnail',
            field=models.ImageField(default='http://placehold.it/1000x600/bfbfbf/ffffff/?text=RW', upload_to=siteapp.models.upload_image_service),
        ),
    ]
