# Generated by Django 2.1 on 2018-09-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0019_auto_20180918_1639'),
        ('siteapp', '0018_merge_20180915_0252'),
    ]

    operations = [
    ]
