# Generated by Django 2.1 on 2018-08-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0020_auto_20180828_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepost',
            name='post_title',
            field=models.CharField(help_text='Enter the post title', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='archiveproject',
            name='project_title',
            field=models.CharField(help_text='Enter the project title', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='archiveservice',
            name='service_title',
            field=models.CharField(help_text='Enter the service title', max_length=200, unique=True),
        ),
    ]
