# Generated by Django 2.0.7 on 2018-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'Ingles'), ('es', 'Spanish')], default='en', help_text='Select the language', max_length=30, null=True),
        ),
    ]
