# Generated by Django 2.0.7 on 2018-07-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text='Enter a Lenguage CODE like (EN or ES)', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of language like: English', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
    ]
