# Generated by Django 2.0.7 on 2018-07-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180710_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('language_code', models.CharField(help_text='Enter a Lenguage CODE like (EN or ES)', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LanguageCode'),
        ),
    ]
