# Generated by Django 2.0.7 on 2018-07-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180710_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language_code',
        ),
        migrations.DeleteModel(
            name='LanguageCode',
        ),
    ]
