# Generated by Django 2.0.7 on 2018-07-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180710_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='Enter a Lenguage CODE like (EN or ES)', max_length=2, primary_key=True, serialize=False),
        ),
    ]
