# Generated by Django 2.0.7 on 2018-07-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180710_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='Enter a Lenguage CODE like (EN or ES)', max_length=2, unique=True),
        ),
    ]
