# Generated by Django 2.0.7 on 2018-07-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
