# Generated by Django 2.0.7 on 2018-07-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
